networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/nginx/sites-available/kartapamyati.ru'
#    depends_on:
#      - backend
#      - backend1
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev
  backend1:
    build:
      context: ./backend
    networks:
      - dev