networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - backend1
    networks:
      - dev

  backend:
    build:
      context: ./backend/src
    networks:
      - dev
  backend1:
    build:
      context: ./backend/src
    networks:
      - dev