networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
#    depends_on:
#      -backend
    network:
      -dev

  backend:
    build:
      context: ./backend
      network:
        -dev